#!/usr/bin/env bash
# Deploy the Student Affairs CMS to this VM. Idempotent: re-running pulls the
# latest main and rebuilds without touching the database or uploaded media.
#
#   /opt/student-affairs/app      git clone of the repo
#   /opt/student-affairs/backups  backup.sh output (see backup.sh)
set -euo pipefail

BASE=/opt/student-affairs
APP="$BASE/app"
REPO=https://github.com/Aonrafay/Student-Affair-Website.git
# Overridable so a branch can be deployed for testing:
#   BRANCH=security-and-backups bash /opt/student-affairs/deploy.sh
BRANCH="${BRANCH:-main}"

step() { echo; echo "===== $* ====="; }

step "source"
if [ -d "$APP/.git" ]; then
  git -C "$APP" fetch --quiet origin "$BRANCH"
  git -C "$APP" checkout --quiet "$BRANCH"
  git -C "$APP" pull --ff-only --quiet origin "$BRANCH"
  echo "updated to $(git -C "$APP" rev-parse --short HEAD)"
else
  git clone --quiet --branch "$BRANCH" "$REPO" "$APP"
  echo "cloned $REPO @ $(git -C "$APP" rev-parse --short HEAD)"
fi

cd "$APP"

step "secrets"
if [ -f .env ]; then
  echo ".env already exists - leaving it alone (secrets are never regenerated)"
else
  # Hex only: no $, #, quotes or backslashes, so Compose's .env parser cannot
  # mangle them and no shell ever expands them.
  JWT_SECRET="$(openssl rand -hex 32)"
  DB_PASSWORD="$(openssl rand -hex 16)"
  MYSQL_ROOT_PASSWORD="$(openssl rand -hex 16)"
  ADMIN_PASSWORD="$(openssl rand -hex 12)"
  EDITOR_PASSWORD="$(openssl rand -hex 12)"

  umask 077
  cat > .env <<EOF
# Generated by deploy.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# git-ignored. Never commit, never paste into chat. Backed up (mode 600) by
# backup.sh into /opt/student-affairs/backups/env/

PORT=5000
BASE_PATH=/student-affairs

JWT_SECRET=$JWT_SECRET

DB_HOST=db
DB_PORT=3306
DB_USER=sa
DB_PASSWORD=$DB_PASSWORD
DB_NAME=student_affairs
MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

ADMIN_EMAIL=admin@niit.edu.pk
ADMIN_PASSWORD=$ADMIN_PASSWORD
EDITOR_EMAIL=editor@niit.edu.pk
EDITOR_PASSWORD=$EDITOR_PASSWORD
EOF
  chmod 600 .env
  echo "wrote .env (mode 600)"

  # Surfaced once, here, so the operator can sign in. Also lives in .env.
  echo
  echo "---- seed logins (seeded only on this first boot) ----"
  echo "  admin  : admin@niit.edu.pk / $ADMIN_PASSWORD"
  echo "  editor : editor@niit.edu.pk / $EDITOR_PASSWORD"
  echo "----------------------------------------------------"
fi

step "compose config is valid"
docker compose config --quiet
echo "ok"

step "build + start"
docker compose up -d --build

step "wait for health"
for i in $(seq 1 60); do
  body="$(curl -fsS --max-time 5 http://127.0.0.1:5000/student-affairs/api/health 2>/dev/null || true)"
  case "$body" in
    *'"ok":true'*) echo "healthy after ${i}0s: $body"; break ;;
  esac
  if [ "$i" -eq 60 ]; then
    echo "TIMED OUT waiting for health endpoint"
    docker compose ps
    docker compose logs --tail 60 app
    exit 1
  fi
  sleep 10
done

step "status"
docker compose ps

step "smoke test"
for p in /student-affairs/ /student-affairs/admin/login /student-affairs/api/health /student-affairs/api/posts; do
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "http://127.0.0.1:5000$p")"
  echo "  $code  $p"
done

step "done"
